/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StatisticalAnomalyClassifierConfiguratorPanel.java
 *
 * Created on 01.07.2011, 15:55:13
 */

package org.bham.aucom.diagnoser.t2gram.detector.anomalyclassifier;

/**
 * @author rgolombe
 */
public class StatisticalAnomalyClassifierConfiguratorPanel extends AnomalyConfiguratorPanel {
    private static final long serialVersionUID = 0L;

    /**
     * Creates new form StatisticalAnomalyClassifierConfiguratorPanel
     */
    public StatisticalAnomalyClassifierConfiguratorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(500, 30));

        jLabel1.setText("mean");
        add(jLabel1);

        jTextField1.setText("0.0");
        jTextField1.setPreferredSize(new java.awt.Dimension(100, 27));
        add(jTextField1);

        jLabel2.setText("variance");
        add(jLabel2);

        jTextField2.setText("0.0");
        jTextField2.setPreferredSize(new java.awt.Dimension(100, 27));
        add(jTextField2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
