/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KernelDensityInputPanel.java
 *
 * Created on 06.08.2010, 14:51:20
 */

package org.bham.aucom.gui;

import org.bham.aucom.diagnoser.t2gram.KDEProbabilityFactory;
import org.bham.aucom.diagnoser.t2gram.ProbabilityFactory;
import org.bham.aucom.models.probability.ProbabilityInputPanel;


/**
 *
 * @author rgolombe
 */
public class KernelDensityInputPanel extends ProbabilityInputPanel {
	private static final long serialVersionUID = 0L;

    /** Creates new form KernelDensityInputPanel */
    public KernelDensityInputPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        precisionTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        precisionTextField.setText("40.0");

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 16));
        jLabel1.setText("precision");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(precisionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(precisionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField precisionTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public ProbabilityFactory getProbabilityFactory() {
    	Double precision = Double.valueOf(this.precisionTextField.getText());
        return new KDEProbabilityFactory(precision);
    }

}
