package org.bham.aucom.main;

public enum SystemModelStatus {
	IDLE,
	TRAININGSTARTED,
	TRAININGSTOPPED,
	TESTSTARTED,
	TESTSTOPPED,
	MODELPARAMETERCHANGED, 
	STATUSCHANGED_TO_FAULT, 
	STATUSCHANGED_TO_OK, 
}
